import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import RootProvider from "@/providers/root-provider";
import { headers } from "next/headers";
import "@coinbase/onchainkit/styles.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { Toaster } from "@/components/ui/toaster";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookies = headers().get("cookie");

	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<RootProvider cookies={cookies}>
					<Header />
					{children}
					<Footer />
					<Toaster />
				</RootProvider>
			</body>
		</html>
	);
}
